name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your deployment branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Or the version your project uses

      - name: Install dependencies
        run: npm install  # Adjust if you're using Yarn or other package managers

      - name: Build project
        run: npm run build  # Or any build command you use (for example, 'npm run build')

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Make sure this matches your output directory
